public enum Codes
{
    CODE_ANALOG,
    CODE_DIGITAL,
    CODE_CUSTOM,
    CODE_LIMITSET,
    CODE_SINGLENODE,
    CODE_MULTIPLENODE,
    CODE_CONSUMER,
    CODE_SOURCE,
    CODE_MOTION,
    CODE_SENSOR
}